west:
  url: https://github.com/zephyrproject-rtos/west
  version: v0.7.2

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos 
    - name: zephyrproject_nuvoton
      url-base: https://github.com/brookliu888/

  projects:
    - name: zephyr
      path: zephyr
      remote: zephyrproject_nuvoton
      revision: 808deb0b135d3a164c8857ce3f61bf19f98a93c0
      clone-depth: 1
      west-commands: scripts/west-commands.yml

    - name: cmsis
      remote: zephyrproject
      revision: 093de61c2a7d12dc9253daf8692f61f793a9254a
      path: modules/hal/cmsis
      groups:
        - hal

  self:
    path: npcx-zephyr